[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem212401
monitor_port = /dev/cu.usbmodem212401

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
  moononournation/GFX Library for Arduino@1.4.7
  bitbank2/AnimatedGIF@^2.1.1
  h2zero/NimBLE-Arduino@^1.4.2