#pragma once

#include <Arduino.h>

// Generated from setup/pitching-battle-outcomes.json
// Regenerate with: python3 setup/generateOutcomes.py

enum PitchOutcomeAction : uint8_t {
  PITCH_ACTION_HOMERUN,
  PITCH_ACTION_TRIPLE,
  PITCH_ACTION_DOUBLE,
  PITCH_ACTION_SINGLE,
  PITCH_ACTION_FOUL,
  PITCH_ACTION_BALL,
  PITCH_ACTION_STRIKE,
  PITCH_ACTION_FLYOUT,
  PITCH_ACTION_GROUNDOUT,
};

struct PitchOutcomeResponse {
  uint8_t weight;
  PitchOutcomeAction action;
  uint16_t textIndex;
};

struct PitchOutcomeEntry {
  uint16_t responseStart;
  uint8_t responseCount;
};

constexpr size_t PITCH_OUTCOME_COMBO_COUNT = 81;
constexpr size_t PITCH_OUTCOME_RESPONSE_COUNT = 434;
constexpr size_t PITCH_OUTCOME_TEXT_COUNT = 149;

const char* const PITCH_OUTCOME_TEXTS[PITCH_OUTCOME_TEXT_COUNT] PROGMEM = {
  "That was a high fast pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a high fast pitch and the batter got every bit of that one. Home run!",
  "That was a high fast pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a high fast pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "He sends it foul down the right line.",
  "A deep pop up to right. The fielder makes the catch.",
  "Grounded to the right side. Easy play at first.",
  "Line drive into right field for a base hit.",
  "That one gets past the outfielder. He is headed for second.",
  "Deep into the right field corner. He is flying around the bases.",
  "He sends it foul down the right side.",
  "A sharp grounder through the right side for a base hit.",
  "Hit right back up the middle, but the defense tracks it down.",
  "Line drive up the middle for a base hit.",
  "Driven deep into center field for extra bases.",
  "That ball rolls all the way to the wall in center.",
  "That was a high fast pitch. The batter swung center and slow, but missed it completely.",
  "The pitcher wins that battle. A high fast pitch gets past the batter for a strike.",
  "Swing and a miss! The high fast pitch was too much for him.",
  "He chased a high fast pitch and came up empty.",
  "The batter offered at the high fast pitch and missed for strike one.",
  "The batter checks his swing and lets the high fast pitch go by. Ball!",
  "He holds up and watches the high fast pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the high fast pitch for a ball.",
  "The batter isn't fooled. He takes the high fast pitch and the umpire calls ball.",
  "The high fast pitch stays outside and the batter wisely lets it pass. Ball.",
  "Right back up the middle, but the defense handles it cleanly.",
  "A chopper up the middle sneaks through for a base hit.",
  "That was a high fast pitch. The batter swung low and medium, but missed it completely.",
  "That was a high fast pitch. The batter swung low and slow, but missed it completely.",
  "He sends it foul down the left line.",
  "A deep pop up to left. The fielder makes the catch.",
  "Grounded to the left side. Easy play at first.",
  "Line drive into left field for a base hit.",
  "Deep into the left field corner. He is flying around the bases.",
  "That was a high medium pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a high medium pitch and the batter got every bit of that one. Home run!",
  "That was a high medium pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a high medium pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "He sends it foul down the left side.",
  "A sharp grounder through the left side for a base hit.",
  "That was a high medium pitch. The batter swung low and fast, but missed it completely.",
  "The pitcher wins that battle. A high medium pitch gets past the batter for a strike.",
  "Swing and a miss! The high medium pitch was too much for him.",
  "He chased a high medium pitch and came up empty.",
  "The batter offered at the high medium pitch and missed for strike one.",
  "The batter checks his swing and lets the high medium pitch go by. Ball!",
  "He holds up and watches the high medium pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the high medium pitch for a ball.",
  "The batter isn't fooled. He takes the high medium pitch and the umpire calls ball.",
  "The high medium pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a high medium pitch. The batter swung low and slow, but missed it completely.",
  "That was a high slow pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a high slow pitch and the batter got every bit of that one. Home run!",
  "That was a high slow pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a high slow pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "That was a high slow pitch. The batter swung center and fast, but missed it completely.",
  "The pitcher wins that battle. A high slow pitch gets past the batter for a strike.",
  "Swing and a miss! The high slow pitch was too much for him.",
  "He chased a high slow pitch and came up empty.",
  "The batter offered at the high slow pitch and missed for strike one.",
  "The batter checks his swing and lets the high slow pitch go by. Ball!",
  "He holds up and watches the high slow pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the high slow pitch for a ball.",
  "The batter isn't fooled. He takes the high slow pitch and the umpire calls ball.",
  "The high slow pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a high slow pitch. The batter swung low and fast, but missed it completely.",
  "That was a high slow pitch. The batter swung low and medium, but missed it completely.",
  "That was a center fast pitch. The batter swung high and slow, but missed it completely.",
  "The pitcher wins that battle. A center fast pitch gets past the batter for a strike.",
  "Swing and a miss! The center fast pitch was too much for him.",
  "He chased a center fast pitch and came up empty.",
  "The batter offered at the center fast pitch and missed for strike one.",
  "The batter checks his swing and lets the center fast pitch go by. Ball!",
  "He holds up and watches the center fast pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the center fast pitch for a ball.",
  "The batter isn't fooled. He takes the center fast pitch and the umpire calls ball.",
  "The center fast pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a center fast pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a center fast pitch and the batter got every bit of that one. Home run!",
  "That was a center fast pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a center fast pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "That was a center fast pitch. The batter swung low and slow, but missed it completely.",
  "That was a center medium pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a center medium pitch and the batter got every bit of that one. Home run!",
  "That was a center medium pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a center medium pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "That was a center slow pitch. The batter swung high and fast, but missed it completely.",
  "The pitcher wins that battle. A center slow pitch gets past the batter for a strike.",
  "Swing and a miss! The center slow pitch was too much for him.",
  "He chased a center slow pitch and came up empty.",
  "The batter offered at the center slow pitch and missed for strike one.",
  "The batter checks his swing and lets the center slow pitch go by. Ball!",
  "He holds up and watches the center slow pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the center slow pitch for a ball.",
  "The batter isn't fooled. He takes the center slow pitch and the umpire calls ball.",
  "The center slow pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a center slow pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a center slow pitch and the batter got every bit of that one. Home run!",
  "That was a center slow pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a center slow pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "That was a center slow pitch. The batter swung low and fast, but missed it completely.",
  "That was a low fast pitch. The batter swung high and medium, but missed it completely.",
  "The pitcher wins that battle. A low fast pitch gets past the batter for a strike.",
  "Swing and a miss! The low fast pitch was too much for him.",
  "He chased a low fast pitch and came up empty.",
  "The batter offered at the low fast pitch and missed for strike one.",
  "The batter checks his swing and lets the low fast pitch go by. Ball!",
  "He holds up and watches the low fast pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the low fast pitch for a ball.",
  "The batter isn't fooled. He takes the low fast pitch and the umpire calls ball.",
  "The low fast pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a low fast pitch. The batter swung high and slow, but missed it completely.",
  "That was a low fast pitch. The batter swung center and slow, but missed it completely.",
  "That was a low fast pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a low fast pitch and the batter got every bit of that one. Home run!",
  "That was a low fast pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a low fast pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "That was a low medium pitch. The batter swung high and fast, but missed it completely.",
  "The pitcher wins that battle. A low medium pitch gets past the batter for a strike.",
  "Swing and a miss! The low medium pitch was too much for him.",
  "He chased a low medium pitch and came up empty.",
  "The batter offered at the low medium pitch and missed for strike one.",
  "The batter checks his swing and lets the low medium pitch go by. Ball!",
  "He holds up and watches the low medium pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the low medium pitch for a ball.",
  "The batter isn't fooled. He takes the low medium pitch and the umpire calls ball.",
  "The low medium pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a low medium pitch. The batter swung high and slow, but missed it completely.",
  "That was a low medium pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a low medium pitch and the batter got every bit of that one. Home run!",
  "That was a low medium pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a low medium pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
  "That was a low slow pitch. The batter swung high and fast, but missed it completely.",
  "The pitcher wins that battle. A low slow pitch gets past the batter for a strike.",
  "Swing and a miss! The low slow pitch was too much for him.",
  "He chased a low slow pitch and came up empty.",
  "The batter offered at the low slow pitch and missed for strike one.",
  "The batter checks his swing and lets the low slow pitch go by. Ball!",
  "He holds up and watches the low slow pitch miss the zone. Ball.",
  "Good eye by the batter. He lays off the low slow pitch for a ball.",
  "The batter isn't fooled. He takes the low slow pitch and the umpire calls ball.",
  "The low slow pitch stays outside and the batter wisely lets it pass. Ball.",
  "That was a low slow pitch. The batter swung high and medium, but missed it completely.",
  "That was a low slow pitch. The batter swung center and fast, but missed it completely.",
  "That was a low slow pitch. The batter matched it perfectly. That ball is crushed! Way back and gone! Home run!",
  "That was a low slow pitch and the batter got every bit of that one. Home run!",
  "That was a low slow pitch. No doubt about it. That one is headed for the bleachers! Home run!",
  "That was a low slow pitch. A towering drive to deep center field and it is out of here! Perfect timing. Home run!",
};

const PitchOutcomeResponse PITCH_OUTCOME_RESPONSES[PITCH_OUTCOME_RESPONSE_COUNT] PROGMEM = {
  { 25, PITCH_ACTION_HOMERUN, 0 },
  { 25, PITCH_ACTION_HOMERUN, 1 },
  { 25, PITCH_ACTION_HOMERUN, 2 },
  { 25, PITCH_ACTION_HOMERUN, 3 },
  { 20, PITCH_ACTION_FOUL, 4 },
  { 20, PITCH_ACTION_FLYOUT, 5 },
  { 20, PITCH_ACTION_GROUNDOUT, 6 },
  { 25, PITCH_ACTION_SINGLE, 7 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 9 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 16 },
  { 10, PITCH_ACTION_STRIKE, 17 },
  { 10, PITCH_ACTION_STRIKE, 18 },
  { 10, PITCH_ACTION_STRIKE, 19 },
  { 10, PITCH_ACTION_STRIKE, 20 },
  { 10, PITCH_ACTION_BALL, 21 },
  { 10, PITCH_ACTION_BALL, 22 },
  { 10, PITCH_ACTION_BALL, 23 },
  { 10, PITCH_ACTION_BALL, 24 },
  { 10, PITCH_ACTION_BALL, 25 },
  { 60, PITCH_ACTION_GROUNDOUT, 26 },
  { 40, PITCH_ACTION_SINGLE, 27 },
  { 10, PITCH_ACTION_STRIKE, 28 },
  { 10, PITCH_ACTION_STRIKE, 17 },
  { 10, PITCH_ACTION_STRIKE, 18 },
  { 10, PITCH_ACTION_STRIKE, 19 },
  { 10, PITCH_ACTION_STRIKE, 20 },
  { 10, PITCH_ACTION_BALL, 21 },
  { 10, PITCH_ACTION_BALL, 22 },
  { 10, PITCH_ACTION_BALL, 23 },
  { 10, PITCH_ACTION_BALL, 24 },
  { 10, PITCH_ACTION_BALL, 25 },
  { 10, PITCH_ACTION_STRIKE, 29 },
  { 10, PITCH_ACTION_STRIKE, 17 },
  { 10, PITCH_ACTION_STRIKE, 18 },
  { 10, PITCH_ACTION_STRIKE, 19 },
  { 10, PITCH_ACTION_STRIKE, 20 },
  { 10, PITCH_ACTION_BALL, 21 },
  { 10, PITCH_ACTION_BALL, 22 },
  { 10, PITCH_ACTION_BALL, 23 },
  { 10, PITCH_ACTION_BALL, 24 },
  { 10, PITCH_ACTION_BALL, 25 },
  { 20, PITCH_ACTION_FOUL, 30 },
  { 20, PITCH_ACTION_FLYOUT, 31 },
  { 20, PITCH_ACTION_GROUNDOUT, 32 },
  { 25, PITCH_ACTION_SINGLE, 33 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 34 },
  { 25, PITCH_ACTION_HOMERUN, 35 },
  { 25, PITCH_ACTION_HOMERUN, 36 },
  { 25, PITCH_ACTION_HOMERUN, 37 },
  { 25, PITCH_ACTION_HOMERUN, 38 },
  { 20, PITCH_ACTION_FOUL, 4 },
  { 20, PITCH_ACTION_FLYOUT, 5 },
  { 20, PITCH_ACTION_GROUNDOUT, 6 },
  { 25, PITCH_ACTION_SINGLE, 7 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 9 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 41 },
  { 10, PITCH_ACTION_STRIKE, 42 },
  { 10, PITCH_ACTION_STRIKE, 43 },
  { 10, PITCH_ACTION_STRIKE, 44 },
  { 10, PITCH_ACTION_STRIKE, 45 },
  { 10, PITCH_ACTION_BALL, 46 },
  { 10, PITCH_ACTION_BALL, 47 },
  { 10, PITCH_ACTION_BALL, 48 },
  { 10, PITCH_ACTION_BALL, 49 },
  { 10, PITCH_ACTION_BALL, 50 },
  { 60, PITCH_ACTION_GROUNDOUT, 26 },
  { 40, PITCH_ACTION_SINGLE, 27 },
  { 10, PITCH_ACTION_STRIKE, 51 },
  { 10, PITCH_ACTION_STRIKE, 42 },
  { 10, PITCH_ACTION_STRIKE, 43 },
  { 10, PITCH_ACTION_STRIKE, 44 },
  { 10, PITCH_ACTION_STRIKE, 45 },
  { 10, PITCH_ACTION_BALL, 46 },
  { 10, PITCH_ACTION_BALL, 47 },
  { 10, PITCH_ACTION_BALL, 48 },
  { 10, PITCH_ACTION_BALL, 49 },
  { 10, PITCH_ACTION_BALL, 50 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 20, PITCH_ACTION_FOUL, 30 },
  { 20, PITCH_ACTION_FLYOUT, 31 },
  { 20, PITCH_ACTION_GROUNDOUT, 32 },
  { 25, PITCH_ACTION_SINGLE, 33 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 34 },
  { 25, PITCH_ACTION_HOMERUN, 52 },
  { 25, PITCH_ACTION_HOMERUN, 53 },
  { 25, PITCH_ACTION_HOMERUN, 54 },
  { 25, PITCH_ACTION_HOMERUN, 55 },
  { 10, PITCH_ACTION_STRIKE, 56 },
  { 10, PITCH_ACTION_STRIKE, 57 },
  { 10, PITCH_ACTION_STRIKE, 58 },
  { 10, PITCH_ACTION_STRIKE, 59 },
  { 10, PITCH_ACTION_STRIKE, 60 },
  { 10, PITCH_ACTION_BALL, 61 },
  { 10, PITCH_ACTION_BALL, 62 },
  { 10, PITCH_ACTION_BALL, 63 },
  { 10, PITCH_ACTION_BALL, 64 },
  { 10, PITCH_ACTION_BALL, 65 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 10, PITCH_ACTION_STRIKE, 66 },
  { 10, PITCH_ACTION_STRIKE, 57 },
  { 10, PITCH_ACTION_STRIKE, 58 },
  { 10, PITCH_ACTION_STRIKE, 59 },
  { 10, PITCH_ACTION_STRIKE, 60 },
  { 10, PITCH_ACTION_BALL, 61 },
  { 10, PITCH_ACTION_BALL, 62 },
  { 10, PITCH_ACTION_BALL, 63 },
  { 10, PITCH_ACTION_BALL, 64 },
  { 10, PITCH_ACTION_BALL, 65 },
  { 10, PITCH_ACTION_STRIKE, 67 },
  { 10, PITCH_ACTION_STRIKE, 57 },
  { 10, PITCH_ACTION_STRIKE, 58 },
  { 10, PITCH_ACTION_STRIKE, 59 },
  { 10, PITCH_ACTION_STRIKE, 60 },
  { 10, PITCH_ACTION_BALL, 61 },
  { 10, PITCH_ACTION_BALL, 62 },
  { 10, PITCH_ACTION_BALL, 63 },
  { 10, PITCH_ACTION_BALL, 64 },
  { 10, PITCH_ACTION_BALL, 65 },
  { 60, PITCH_ACTION_GROUNDOUT, 26 },
  { 40, PITCH_ACTION_SINGLE, 27 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 68 },
  { 10, PITCH_ACTION_STRIKE, 69 },
  { 10, PITCH_ACTION_STRIKE, 70 },
  { 10, PITCH_ACTION_STRIKE, 71 },
  { 10, PITCH_ACTION_STRIKE, 72 },
  { 10, PITCH_ACTION_BALL, 73 },
  { 10, PITCH_ACTION_BALL, 74 },
  { 10, PITCH_ACTION_BALL, 75 },
  { 10, PITCH_ACTION_BALL, 76 },
  { 10, PITCH_ACTION_BALL, 77 },
  { 25, PITCH_ACTION_HOMERUN, 78 },
  { 25, PITCH_ACTION_HOMERUN, 79 },
  { 25, PITCH_ACTION_HOMERUN, 80 },
  { 25, PITCH_ACTION_HOMERUN, 81 },
  { 20, PITCH_ACTION_FOUL, 4 },
  { 20, PITCH_ACTION_FLYOUT, 5 },
  { 20, PITCH_ACTION_GROUNDOUT, 6 },
  { 25, PITCH_ACTION_SINGLE, 7 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 9 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 82 },
  { 10, PITCH_ACTION_STRIKE, 69 },
  { 10, PITCH_ACTION_STRIKE, 70 },
  { 10, PITCH_ACTION_STRIKE, 71 },
  { 10, PITCH_ACTION_STRIKE, 72 },
  { 10, PITCH_ACTION_BALL, 73 },
  { 10, PITCH_ACTION_BALL, 74 },
  { 10, PITCH_ACTION_BALL, 75 },
  { 10, PITCH_ACTION_BALL, 76 },
  { 10, PITCH_ACTION_BALL, 77 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 20, PITCH_ACTION_FOUL, 30 },
  { 20, PITCH_ACTION_FLYOUT, 31 },
  { 20, PITCH_ACTION_GROUNDOUT, 32 },
  { 25, PITCH_ACTION_SINGLE, 33 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 34 },
  { 25, PITCH_ACTION_HOMERUN, 83 },
  { 25, PITCH_ACTION_HOMERUN, 84 },
  { 25, PITCH_ACTION_HOMERUN, 85 },
  { 25, PITCH_ACTION_HOMERUN, 86 },
  { 20, PITCH_ACTION_FOUL, 4 },
  { 20, PITCH_ACTION_FLYOUT, 5 },
  { 20, PITCH_ACTION_GROUNDOUT, 6 },
  { 25, PITCH_ACTION_SINGLE, 7 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 9 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 87 },
  { 10, PITCH_ACTION_STRIKE, 88 },
  { 10, PITCH_ACTION_STRIKE, 89 },
  { 10, PITCH_ACTION_STRIKE, 90 },
  { 10, PITCH_ACTION_STRIKE, 91 },
  { 10, PITCH_ACTION_BALL, 92 },
  { 10, PITCH_ACTION_BALL, 93 },
  { 10, PITCH_ACTION_BALL, 94 },
  { 10, PITCH_ACTION_BALL, 95 },
  { 10, PITCH_ACTION_BALL, 96 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 20, PITCH_ACTION_FOUL, 30 },
  { 20, PITCH_ACTION_FLYOUT, 31 },
  { 20, PITCH_ACTION_GROUNDOUT, 32 },
  { 25, PITCH_ACTION_SINGLE, 33 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 34 },
  { 25, PITCH_ACTION_HOMERUN, 97 },
  { 25, PITCH_ACTION_HOMERUN, 98 },
  { 25, PITCH_ACTION_HOMERUN, 99 },
  { 25, PITCH_ACTION_HOMERUN, 100 },
  { 10, PITCH_ACTION_STRIKE, 101 },
  { 10, PITCH_ACTION_STRIKE, 88 },
  { 10, PITCH_ACTION_STRIKE, 89 },
  { 10, PITCH_ACTION_STRIKE, 90 },
  { 10, PITCH_ACTION_STRIKE, 91 },
  { 10, PITCH_ACTION_BALL, 92 },
  { 10, PITCH_ACTION_BALL, 93 },
  { 10, PITCH_ACTION_BALL, 94 },
  { 10, PITCH_ACTION_BALL, 95 },
  { 10, PITCH_ACTION_BALL, 96 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 60, PITCH_ACTION_GROUNDOUT, 26 },
  { 40, PITCH_ACTION_SINGLE, 27 },
  { 10, PITCH_ACTION_STRIKE, 102 },
  { 10, PITCH_ACTION_STRIKE, 103 },
  { 10, PITCH_ACTION_STRIKE, 104 },
  { 10, PITCH_ACTION_STRIKE, 105 },
  { 10, PITCH_ACTION_STRIKE, 106 },
  { 10, PITCH_ACTION_BALL, 107 },
  { 10, PITCH_ACTION_BALL, 108 },
  { 10, PITCH_ACTION_BALL, 109 },
  { 10, PITCH_ACTION_BALL, 110 },
  { 10, PITCH_ACTION_BALL, 111 },
  { 10, PITCH_ACTION_STRIKE, 112 },
  { 10, PITCH_ACTION_STRIKE, 103 },
  { 10, PITCH_ACTION_STRIKE, 104 },
  { 10, PITCH_ACTION_STRIKE, 105 },
  { 10, PITCH_ACTION_STRIKE, 106 },
  { 10, PITCH_ACTION_BALL, 107 },
  { 10, PITCH_ACTION_BALL, 108 },
  { 10, PITCH_ACTION_BALL, 109 },
  { 10, PITCH_ACTION_BALL, 110 },
  { 10, PITCH_ACTION_BALL, 111 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 113 },
  { 10, PITCH_ACTION_STRIKE, 103 },
  { 10, PITCH_ACTION_STRIKE, 104 },
  { 10, PITCH_ACTION_STRIKE, 105 },
  { 10, PITCH_ACTION_STRIKE, 106 },
  { 10, PITCH_ACTION_BALL, 107 },
  { 10, PITCH_ACTION_BALL, 108 },
  { 10, PITCH_ACTION_BALL, 109 },
  { 10, PITCH_ACTION_BALL, 110 },
  { 10, PITCH_ACTION_BALL, 111 },
  { 25, PITCH_ACTION_HOMERUN, 114 },
  { 25, PITCH_ACTION_HOMERUN, 115 },
  { 25, PITCH_ACTION_HOMERUN, 116 },
  { 25, PITCH_ACTION_HOMERUN, 117 },
  { 20, PITCH_ACTION_FOUL, 4 },
  { 20, PITCH_ACTION_FLYOUT, 5 },
  { 20, PITCH_ACTION_GROUNDOUT, 6 },
  { 25, PITCH_ACTION_SINGLE, 7 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 9 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 10, PITCH_ACTION_STRIKE, 118 },
  { 10, PITCH_ACTION_STRIKE, 119 },
  { 10, PITCH_ACTION_STRIKE, 120 },
  { 10, PITCH_ACTION_STRIKE, 121 },
  { 10, PITCH_ACTION_STRIKE, 122 },
  { 10, PITCH_ACTION_BALL, 123 },
  { 10, PITCH_ACTION_BALL, 124 },
  { 10, PITCH_ACTION_BALL, 125 },
  { 10, PITCH_ACTION_BALL, 126 },
  { 10, PITCH_ACTION_BALL, 127 },
  { 60, PITCH_ACTION_GROUNDOUT, 26 },
  { 40, PITCH_ACTION_SINGLE, 27 },
  { 10, PITCH_ACTION_STRIKE, 128 },
  { 10, PITCH_ACTION_STRIKE, 119 },
  { 10, PITCH_ACTION_STRIKE, 120 },
  { 10, PITCH_ACTION_STRIKE, 121 },
  { 10, PITCH_ACTION_STRIKE, 122 },
  { 10, PITCH_ACTION_BALL, 123 },
  { 10, PITCH_ACTION_BALL, 124 },
  { 10, PITCH_ACTION_BALL, 125 },
  { 10, PITCH_ACTION_BALL, 126 },
  { 10, PITCH_ACTION_BALL, 127 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 10 },
  { 40, PITCH_ACTION_GROUNDOUT, 6 },
  { 40, PITCH_ACTION_SINGLE, 11 },
  { 20, PITCH_ACTION_FOUL, 30 },
  { 20, PITCH_ACTION_FLYOUT, 31 },
  { 20, PITCH_ACTION_GROUNDOUT, 32 },
  { 25, PITCH_ACTION_SINGLE, 33 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 34 },
  { 25, PITCH_ACTION_HOMERUN, 129 },
  { 25, PITCH_ACTION_HOMERUN, 130 },
  { 25, PITCH_ACTION_HOMERUN, 131 },
  { 25, PITCH_ACTION_HOMERUN, 132 },
  { 20, PITCH_ACTION_FOUL, 4 },
  { 20, PITCH_ACTION_FLYOUT, 5 },
  { 20, PITCH_ACTION_GROUNDOUT, 6 },
  { 25, PITCH_ACTION_SINGLE, 7 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 9 },
  { 10, PITCH_ACTION_STRIKE, 133 },
  { 10, PITCH_ACTION_STRIKE, 134 },
  { 10, PITCH_ACTION_STRIKE, 135 },
  { 10, PITCH_ACTION_STRIKE, 136 },
  { 10, PITCH_ACTION_STRIKE, 137 },
  { 10, PITCH_ACTION_BALL, 138 },
  { 10, PITCH_ACTION_BALL, 139 },
  { 10, PITCH_ACTION_BALL, 140 },
  { 10, PITCH_ACTION_BALL, 141 },
  { 10, PITCH_ACTION_BALL, 142 },
  { 10, PITCH_ACTION_STRIKE, 143 },
  { 10, PITCH_ACTION_STRIKE, 134 },
  { 10, PITCH_ACTION_STRIKE, 135 },
  { 10, PITCH_ACTION_STRIKE, 136 },
  { 10, PITCH_ACTION_STRIKE, 137 },
  { 10, PITCH_ACTION_BALL, 138 },
  { 10, PITCH_ACTION_BALL, 139 },
  { 10, PITCH_ACTION_BALL, 140 },
  { 10, PITCH_ACTION_BALL, 141 },
  { 10, PITCH_ACTION_BALL, 142 },
  { 60, PITCH_ACTION_GROUNDOUT, 26 },
  { 40, PITCH_ACTION_SINGLE, 27 },
  { 10, PITCH_ACTION_STRIKE, 144 },
  { 10, PITCH_ACTION_STRIKE, 134 },
  { 10, PITCH_ACTION_STRIKE, 135 },
  { 10, PITCH_ACTION_STRIKE, 136 },
  { 10, PITCH_ACTION_STRIKE, 137 },
  { 10, PITCH_ACTION_BALL, 138 },
  { 10, PITCH_ACTION_BALL, 139 },
  { 10, PITCH_ACTION_BALL, 140 },
  { 10, PITCH_ACTION_BALL, 141 },
  { 10, PITCH_ACTION_BALL, 142 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 50, PITCH_ACTION_FLYOUT, 12 },
  { 35, PITCH_ACTION_SINGLE, 13 },
  { 10, PITCH_ACTION_DOUBLE, 14 },
  { 5, PITCH_ACTION_TRIPLE, 15 },
  { 20, PITCH_ACTION_FOUL, 39 },
  { 40, PITCH_ACTION_GROUNDOUT, 32 },
  { 40, PITCH_ACTION_SINGLE, 40 },
  { 20, PITCH_ACTION_FOUL, 30 },
  { 20, PITCH_ACTION_FLYOUT, 31 },
  { 20, PITCH_ACTION_GROUNDOUT, 32 },
  { 25, PITCH_ACTION_SINGLE, 33 },
  { 10, PITCH_ACTION_DOUBLE, 8 },
  { 5, PITCH_ACTION_TRIPLE, 34 },
  { 25, PITCH_ACTION_HOMERUN, 145 },
  { 25, PITCH_ACTION_HOMERUN, 146 },
  { 25, PITCH_ACTION_HOMERUN, 147 },
  { 25, PITCH_ACTION_HOMERUN, 148 },
};

const PitchOutcomeEntry PITCH_OUTCOME_ENTRIES[PITCH_OUTCOME_COMBO_COUNT] PROGMEM = {
  { 0, 4 },
  { 4, 6 },
  { 10, 3 },
  { 13, 4 },
  { 17, 3 },
  { 20, 10 },
  { 30, 2 },
  { 32, 10 },
  { 42, 10 },
  { 52, 6 },
  { 58, 4 },
  { 62, 6 },
  { 68, 3 },
  { 71, 4 },
  { 75, 3 },
  { 78, 10 },
  { 88, 2 },
  { 90, 10 },
  { 100, 3 },
  { 103, 6 },
  { 109, 4 },
  { 113, 10 },
  { 123, 3 },
  { 126, 4 },
  { 130, 10 },
  { 140, 10 },
  { 150, 2 },
  { 152, 4 },
  { 156, 3 },
  { 159, 10 },
  { 169, 4 },
  { 173, 6 },
  { 179, 3 },
  { 182, 4 },
  { 186, 3 },
  { 189, 10 },
  { 199, 3 },
  { 202, 4 },
  { 206, 3 },
  { 209, 6 },
  { 215, 4 },
  { 219, 6 },
  { 225, 3 },
  { 228, 4 },
  { 232, 3 },
  { 235, 10 },
  { 245, 3 },
  { 248, 4 },
  { 252, 3 },
  { 255, 6 },
  { 261, 4 },
  { 265, 10 },
  { 275, 3 },
  { 278, 4 },
  { 282, 2 },
  { 284, 10 },
  { 294, 10 },
  { 304, 4 },
  { 308, 3 },
  { 311, 10 },
  { 321, 4 },
  { 325, 6 },
  { 331, 3 },
  { 334, 10 },
  { 344, 2 },
  { 346, 10 },
  { 356, 3 },
  { 359, 4 },
  { 363, 3 },
  { 366, 6 },
  { 372, 4 },
  { 376, 6 },
  { 382, 10 },
  { 392, 10 },
  { 402, 2 },
  { 404, 10 },
  { 414, 3 },
  { 417, 4 },
  { 421, 3 },
  { 424, 6 },
  { 430, 4 },
};
